### ISSUE TITLE
Proposal to use [Magefile](https://magefile.org/) for build management

### ISSUE THREAD

**Issue by ccamel** [axone-protocol/axone-contract-schema#24]
## Proposal to adopt Magefile for build management

**Discussion Participants:** @bdeneux, @amimart, @ccamel 

### Current situation

Our current build processes are entirely handled through [GitHub Actions](https://github.com/axone-protocol/axone-contract-schema/blob/main/.github/workflows/update-schema.yml#L82), which manages various tasks directly within the GitHub CI pipeline. While functional, this setup lacks a dedicated build management system, making it challenging to maintain and scale efficiently as our project grows and attracts more contributors.

### Overview

This proposal recommends the adoption of [Magefile](https://magefile.org/) as our primary build management tool. By leveraging the Go programming language, Magefile introduces a modernized approach to managing and automating builds.

![Built with Mage](https://magefile.org/badge.svg)

Implementing Magefile will streamline our build processes, enhance portability across different environments, and improve the overall development experience for both current developers and new contributors.

### Rationale

- **Improved readability and maintainability**: Magefiles, written in Go, offer superior readability and maintainability compared to traditional Makefile syntax. This change will simplify our build scripts, making them more accessible and easier to manage, particularly for those familiar with Go.
- **Platform independence**: Unlike the current reliance on Unix-specific features in some of our scripts, Magefile is inherently cross-platform. Adopting Magefile will eliminate platform-specific issues and standardize our build process across all environments.
- **Enhanced dependency management**: With Magefile, dependencies are explicitly defined within build tasks, which improves the clarity and management of task dependencies and execution order.
- **Robust community support**: Despite the extensive community surrounding traditional Makefiles, the growing community and ecosystem of Magefile provide continuous improvements and robust support, enhancing our development practices.
- **Integration with existing tools**: Magefile can seamlessly integrate with GitHub Actions, allowing us to enhance our current CI/CD pipelines rather than replacing them. This integration will enable more sophisticated build scenarios while maintaining the ease of use and flexibility that GitHub Actions provides.

**Comment by bdeneux** [comment]
![im-on-it](https://github.com/axone-protocol/axone-contract-schema/assets/33665639/a298903a-5f40-4f12-87e1-967e824330a8)
